### ISSUE TITLE
Hats are sometimes able to be selected

### ISSUE THREAD

**Issue by Zeloii** [presssssure/team-create-hats#12]
![GifHolder4](https://user-images.githubusercontent.com/28994186/111202729-36709780-8592-11eb-9bd7-9c5a2c6e3703.gif)

**Comment by presssssure** [comment]
could you provide some hats with positions that this happens with? i can't seem to recreate the bug

**Comment by Zeloii** [comment]
The hats I am currently using are:

1080951
397902264
738679517
4187109081
4239688822

**Comment by presssssure** [comment]
Fixed in 4.1.2!
