### ISSUE TITLE
Update Deprecated Functions

### ISSUE THREAD

**Issue by jameskyvo** [presssssure/team-create-hats#20]
16:17:25.926  GetCollisionGroupId is deprecated. More info: https://devforum.roblox.com/t/updates-to-collision-groups/1990215  -  Studio
  16:17:26.014  SetPartCollisionGroup is deprecated, please use BasePart.CollisionGroup instead. More info: https://devforum.roblox.com/t/updates-to-collision-groups/1990215 
  
  The plugin throws these warnings in my console when selected, warnings dissappear when I unselect the plugin so I assume its the cause of the issue.

**Comment by presssssure** [comment]
Thanks! I'll fix this in the upcoming week

**Comment by presssssure** [comment]
done with cb7b2a9! new release should have the fix
